[package]
name = "ischnix"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ischnix"

[lib]
path = "./src/shared.rs"

[dependencies]
binary-tree = "0.2.0"
libloading = "0.8"
ratatui = "*"
tree-sitter = "0.20.10"
tree-sitter-rust="0.20.3"
crossterm="0.25"

[build-dependencies]
cc="*"
